# Generated by Django 4.0.4 on 2022-04-11 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=128, verbose_name='카테고리 이름')),
                ('description', models.TextField(verbose_name='카테고리 설명')),
                ('share', models.BooleanField(verbose_name='공유 여부')),
                ('scrap', models.IntegerField(default=0, verbose_name='스크랩 횟수')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='카테고리 사용자 id')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_url', models.CharField(default='', max_length=128, verbose_name='링크 주소')),
                ('description', models.TextField(verbose_name='링크 설명')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPage.category', verbose_name='카테고리 id')),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
