# Generated by Django 4.0.4 on 2022-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(default='', verbose_name='링크 설명'),
        ),
    ]
