# Generated by Django 4.0.4 on 2022-05-01 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0002_alter_link_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
